# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20161122_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='birthdate',
            field=models.DateField(blank=True, help_text='дд.мм.гггг', null=True, verbose_name='Дата рождения'),
        ),
    ]
